<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
                <h1 class="h2">Controle de despesas</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a class="btn btn-primary mr-3" href="/inserir_form" role="button">Adicionar despesa</a>
                    <div class="btn-group me-2">
                        <button type="button" class="btn btn-sm btn-outline-secondary">export excel</button>
                    </div>
                </div>
</div>

<form action="/busca" method="post">
  <div class="form-row mb-3">
    <div class="col-md-1">
      <input type="number" class="form-control" name="id" placeholder="ID">
    </div>
    <div class="col-md-2">
      <input name="data" type="date" class="form-control">
    </div>
    <div class="col-md-2">
        <input type="number" min="100000" step="100" class="form-control" name="centro_custo" placeholder="Ex: 100100">
    </div>
    <div class="col-md-2">
      <input name="fornecedor" type="text" class="form-control" placeholder="Fornecedor">
    </div>
    <div class="col-md-2">
        <select class="form-control" id="status" name="status">
        <option value="">Selecione</option>
        <option value="1">Pago</option>
        <option value="2">Pendente</option>
        <option value="3">Agendado</option>
        <option value="4">Realizado acordo</option>
        </select>
    </div>
    <div class="col-md-2">
      <input name="descricao" type="text" class="form-control" placeholder="Descrição">
    </div>
  <button type="submit" class="border-0 btn btn-secondary"><i class="fa-solid fa-magnifying-glass"></i></button>
  </div>
</form>

<div class="table-responsive">
            <table class="table table-striped table-sm">
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Data</th>
                <th scope="col">Centro de custo</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Valor</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach($this->view->despesas as $key => $despesa) {
                ?>
                <tr>
                <td><?= $despesa['id'] ?></td>
                <td><?= $despesa['dt_lancamento'] ?></td>
                <td><?= $despesa['centro_custo'] ?></td>
                <td><?= $despesa['nome_fornecedor'] ?></td>
                <td>R$ <?php echo str_replace('.', ',', $despesa['valor']) ?></td>

                <?php
                $status;
                if ($despesa['status_pag'] == 1) {
                    $status = 'Pago';
                } else if($despesa['status_pag'] == 2) {
                    $status = 'Pendente';
                } else if ($despesa['status_pag'] == 3) {
                    $status = 'Agendado';
                } else {
                    $status = 'Realizar acordo';
                }
                ?>
                <td><?= $status ?></td>

                <td><a class="mr-2" href="/detalhes?id=<?= $despesa['id'] ?>"><i class="fa-solid fa-magnifying-glass text-success"></i></a></td>

                <td>
                    <form action="/editar_form?id=<?= $despesa['id'] ?>" method="post">
                        <button class="border-0" type="submit"><i class="fa-solid fa-pen-to-square text-primary"></i></button>
                    </form>
                </td>

                <td>
                    <form action="/deletar?id=<?= $despesa['id'] ?>" method="post">
                        <button class="border-0" type="submit"><i class="fa-solid fa-trash-can text-danger"></i></button>
                    </form>
                </td>

                </tr>

                <?php
                    }
                ?>
            </tbody>
            </table>
</div>
<small>Clique na lupa para exibir os detalhes</small>