<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Controle de Despesas</title>  

    <link href="/assets/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/custom/css/style.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bb3315e9fa.js" crossorigin="anonymous"></script>
    
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <nav class="navbar">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
            <img src="/assets/img_logo/logo.png" alt="Logo" width="40" height="34" class="d-inline-block align-text-top">
            <strong class="ml-2">Controle de Despesas</strong>
            </a>
        </div>
    </nav>
    </header>

       
    <div class="container">

        <!-- Conteúdo -->
        <?php
            $this->content();
        ?>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    
</body>
</html>